### ISSUE TITLE
Player continues to play the jump animation when pressing up and the A or D keys. 

### ISSUE THREAD

**Issue by rodprogramdev** [gamkedo-la/robo-explorer-2#6]
It looks like the player is swimming while he is trying to fly with the jet pack.

**Comment by oneseedfruit** [comment]
Fix attempt in https://github.com/gamkedo-la/robo-explorer-2/commit/607a60b38b9b71b9bfd44887d682b08463ccdb97

**Comment by rodprogramdev** [comment]
Hi, I'll be closing this issue now. Thank you for solving this bug. Great job.
